
build:
    stage: deploy
    script:
       - cp .env.example .env
       - scp -r . root@192.168.1.185:/var/www/fileserver
       - rm -rf ~/builds
       - ssh root@192.168.1.185 "chown -R nginx. /var/www/fileserver && exit"
       - ssh root@192.168.1.185 "cd /var/www/fileserver && composer install && exit"
# chmod -R 777 /var/www/fileserver